/**
 * Generated by scripts/pwa/generate-icons.ts — do not edit by hand.
 */

export const APPLE_STARTUP_IMAGES = [
  {
    "url": "/splash/iphone-se-1.png",
    "media": "(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)"
  },
  {
    "url": "/splash/iphone-8.png",
    "media": "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)"
  },
  {
    "url": "/splash/iphone-8-plus.png",
    "media": "(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3)"
  },
  {
    "url": "/splash/iphone-x.png",
    "media": "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)"
  },
  {
    "url": "/splash/iphone-xr.png",
    "media": "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2)"
  },
  {
    "url": "/splash/iphone-xs-max.png",
    "media": "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3)"
  },
  {
    "url": "/splash/iphone-12.png",
    "media": "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3)"
  },
  {
    "url": "/splash/iphone-12-pro-max.png",
    "media": "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3)"
  },
  {
    "url": "/splash/iphone-13-mini.png",
    "media": "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)"
  },
  {
    "url": "/splash/iphone-14-pro.png",
    "media": "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3)"
  },
  {
    "url": "/splash/iphone-14-pro-max.png",
    "media": "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3)"
  },
  {
    "url": "/splash/iphone-16-pro.png",
    "media": "(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3)"
  },
  {
    "url": "/splash/iphone-16-pro-max.png",
    "media": "(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3)"
  }
] as const;
