/**
 * Rasterises public/icon.svg into the PNGs the manifest and iOS need, and
 * generates the Apple startup images.
 *
 * iOS only uses a startup image when its media query matches the device
 * exactly, so there is one entry per screen geometry rather than a generic
 * fallback. Keep this list in sync with `appleWebApp.startupImage` in
 * src/app/layout.tsx.
 *
 * Usage: npm run pwa:icons
 */

import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import sharp from 'sharp';

const BACKGROUND = '#0B0B0F';
const publicDir = join(process.cwd(), 'public');
const iconsDir = join(publicDir, 'icons');
const splashDir = join(publicDir, 'splash');

interface IconSpec {
  name: string;
  size: number;
  /** Inset the artwork so Android's maskable crop cannot clip it. */
  padding?: number;
  /** iOS composites its own rounded mask and rejects transparency. */
  flatten?: boolean;
}

const ICONS: IconSpec[] = [
  { name: 'icon-192.png', size: 192 },
  { name: 'icon-512.png', size: 512 },
  { name: 'apple-touch-icon.png', size: 180, flatten: true },
  { name: 'maskable-512.png', size: 512, padding: 90 },
];

/** Device geometries: [width, height, scale, label]. */
const SPLASH_SCREENS: Array<[number, number, number, string]> = [
  [320, 568, 2, 'iphone-se-1'],
  [375, 667, 2, 'iphone-8'],
  [414, 736, 3, 'iphone-8-plus'],
  [375, 812, 3, 'iphone-x'],
  [414, 896, 2, 'iphone-xr'],
  [414, 896, 3, 'iphone-xs-max'],
  [390, 844, 3, 'iphone-12'],
  [428, 926, 3, 'iphone-12-pro-max'],
  [375, 812, 3, 'iphone-13-mini'],
  [393, 852, 3, 'iphone-14-pro'],
  [430, 932, 3, 'iphone-14-pro-max'],
  [402, 874, 3, 'iphone-16-pro'],
  [440, 956, 3, 'iphone-16-pro-max'],
];

async function generateIcons(svg: Buffer) {
  await mkdir(iconsDir, { recursive: true });

  for (const { name, size, padding, flatten } of ICONS) {
    const destination = join(iconsDir, name);

    if (padding) {
      const inner = await sharp(svg).resize(size - padding * 2, size - padding * 2).png().toBuffer();
      await sharp({
        create: { width: size, height: size, channels: 4, background: BACKGROUND },
      })
        .composite([{ input: inner, gravity: 'centre' }])
        .png()
        .toFile(destination);
    } else {
      let pipeline = sharp(svg).resize(size, size);
      if (flatten) pipeline = pipeline.flatten({ background: BACKGROUND });
      await pipeline.png().toFile(destination);
    }

    console.log(`   ✓ icons/${name} (${size}×${size})`);
  }
}

async function generateSplashScreens(svg: Buffer) {
  await mkdir(splashDir, { recursive: true });

  for (const [width, height, scale, label] of SPLASH_SCREENS) {
    const pixelWidth = width * scale;
    const pixelHeight = height * scale;
    const logoSize = Math.round(Math.min(pixelWidth, pixelHeight) * 0.32);
    const logo = await sharp(svg).resize(logoSize, logoSize).png().toBuffer();

    await sharp({
      create: { width: pixelWidth, height: pixelHeight, channels: 4, background: BACKGROUND },
    })
      .composite([{ input: logo, gravity: 'centre' }])
      .png()
      .toFile(join(splashDir, `${label}.png`));

    console.log(`   ✓ splash/${label}.png (${pixelWidth}×${pixelHeight})`);
  }
}

/** Emits the media-query list so layout.tsx never drifts from the files. */
async function writeStartupImageManifest() {
  const entries = SPLASH_SCREENS.map(([width, height, scale, label]) => ({
    url: `/splash/${label}.png`,
    media:
      `(device-width: ${width}px) and (device-height: ${height}px) ` +
      `and (-webkit-device-pixel-ratio: ${scale})`,
  }));

  await writeFile(
    join(process.cwd(), 'src', 'lib', 'apple-splash.ts'),
    `/**\n * Generated by scripts/pwa/generate-icons.ts — do not edit by hand.\n */\n\n` +
      `export const APPLE_STARTUP_IMAGES = ${JSON.stringify(entries, null, 2)} as const;\n`
  );

  console.log(`   ✓ src/lib/apple-splash.ts (${entries.length} entradas)`);
}

async function main() {
  console.log('🎨 Generando iconos y splash screens\n');

  const svg = await readFile(join(publicDir, 'icon.svg'));

  await generateIcons(svg);
  await generateSplashScreens(svg);
  await writeStartupImageManifest();

  console.log('\n✅ Listo.\n');
}

main().catch((error) => {
  console.error('❌ Error:', error);
  process.exit(1);
});
